conferences:
  - name: "CVPR"
    reference_papers:
      - "reference_papers/cvpr_paper1.pdf"
  - name: "NeurIPS"
    reference_papers:
      - "reference_papers/neurips_paper1.pdf"
  - name: "DAA"
    reference_papers: []
  - name: "EMNLP"
    reference_papers: []
  - name: "TMLR"
    reference_papers: []
  - name: "KDD"
    reference_papers: []

paper_data:
  path: "research_paper.txt"