import pandas as pd

# Load the two CSV files generated by script1.py and script2.py
df1 = pd.read_csv('predictions.csv')  # Conference recommendations
df2 = pd.read_csv('conference_recommendations.csv')  # Publishability labels

# Print column names to debug
print("Columns in df1:", df1.columns)
print("Columns in df2:", df2.columns)

# Merge the two DataFrames on the 'file_name' column
combined_df = pd.merge(df1, df2, on='file_name', how='inner')  # Use the correct column name
# Save the combined DataFrame to a new CSV file
combined_df.to_csv('combined_output.csv', index=False)

print("Combined CSV saved to 'combined_output.csv'.")

